adminka/adminka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("", include("apps.users.urls")),
    path("products/", include("apps.products.urls")),
    path("tags/", include("apps.tags.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("shipments/", include("apps.shipments.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "apps.base.views.not_found_view"

adminka/apps/notifications/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.view_all_notifications, name="view-notifications"),
    path("<int:pk>", views.view_notification, name="view-notification"),
    path("create", views.create_notification, name="create-notification"),
    path("<int:pk>/update", views.update_notification, name="update-notification"),
    path("<int:pk>/delete", views.delete_notification, name="delete-notification"),
]

adminka/apps/notifications/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Notification(models.Model):
    NOTIFICATION_TYPES = [
        ("success", "Positive"),
        ("warning", "Warning"),
        ("danger", "Error"),
        ("info", "Info"),
    ]

    text = models.CharField(max_length=155, null=False, blank=False)
    allow_dates = models.BooleanField(
        null=True, default=True, blank=True
    )  # display dates on home page or not
    type = models.CharField(
        null=False, blank=False, choices=NOTIFICATION_TYPES, max_length=15
    )
    start = models.DateTimeField(null=False, blank=False)
    end = models.DateTimeField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(null=True, blank=True)

    def delete(self):
        self.deleted = timezone.now()
        self.save()

    def __str__(self):
        return f"{self.text[:15]}.. {self.start.strftime('%Y-%m-%d')}"

    class Meta:
        verbose_name = "notification"
        verbose_name_plural = "notifications"

adminka/apps/notifications/forms.py
from django import forms
from django.forms.widgets import TextInput, CheckboxInput, Select, DateInput
from .models import Notification


class NotificationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["allow_dates"].required = True

    NOTIFICATION_TYPES = [
        ("success", "Positive"),
        ("warning", "Warning"),
        ("danger", "Error"),
        ("info", "Info"),
    ]

    text = forms.CharField(
        max_length=100,
        widget=TextInput(attrs={"type": "text", "class": "form-control"}),
    )

    type = forms.ChoiceField(
        choices=NOTIFICATION_TYPES,
        widget=Select(attrs={"class": "form-control"}),
    )

    start = forms.DateField(
        widget=DateInput(attrs={"type": "date", "class": "form-control"}),
    )

    end = forms.DateField(
        widget=DateInput(attrs={"type": "date", "class": "form-control"}),
    )

    allow_dates = forms.BooleanField(
        required=False,
        widget=CheckboxInput(attrs={"class": "form-check-input"}),
    )

    class Meta:
        model = Notification
        fields = ["text", "type", "start", "end", "allow_dates"]


class ViewNotification(NotificationForm):
    def __init__(self, *args, **kwargs):
        super(ViewNotification, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"disabled": "True"})

adminka/apps/notifications/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .models import Notification
from .filters import NotificationFilter
from django.urls import reverse
from django.core.paginator import Paginator
from .forms import NotificationForm, ViewNotification
from django.utils import timezone

# Create your views here.
@login_required(login_url="login")
@permission_required("notifications.view_notification", login_url="login")
def view_all_notifications(request):
    filter = NotificationFilter(
        request.GET, queryset=Notification.objects.filter(deleted__isnull=True).order_by("end")
    )
    paginator = Paginator(filter.qs, 20)
    if request.GET.get("page"):
        page_num = request.GET.get("page")
    else:
        page_num = 1
    notifications = paginator.page(page_num)
    context = {"notifications": notifications, "filter": filter}
    return render(request, "notifications/notifications.html", context)


@login_required(login_url="login")
@permission_required("notifications.view_notification", login_url="login")
def view_notification(request, pk):
    notification = Notification.objects.get(id=pk)
    form = ViewNotification(instance=notification)
    context = {"notification": notification, "form":form}
    return render(request, "notifications/view-notification.html", context)


@login_required(login_url="login")
@permission_required("notifications.change_notification", login_url="login")
def update_notification(request, pk):
    notification = Notification.objects.get(id=pk)
    form = NotificationForm(instance=notification, use_required_attribute=False)
    if request.method == "POST":
        form = NotificationForm(request.POST, instance=notification, use_required_attribute=False)
        if form.is_valid():
            notification = form.save()
            return redirect("view-notification", notification.id)
    context = {"notification": notification, "form": form}
    return render(request, "notifications/update-notification.html", context)


@login_required(login_url="login")
@permission_required("notifications.delete_notification", login_url="login")
def delete_notification(request, pk):
    notification = Notification.objects.get(id=pk)
    notification.deleted = timezone.now()
    notification.save()
    return redirect("view-notifications")


@login_required(login_url="login")
@permission_required("notifications.add_notification", login_url="login")
def create_notification(request):
    form = NotificationForm(use_required_attribute=False)
    context = {"form": form}
    if request.method == "POST":
        form = NotificationForm(request.POST)
        if form.is_valid():
            notification = form.save()
            return redirect("view-notifications")
    return render(request, "notifications/create-notification.html", context)

adminka/templates/notifications/create-notification.html
{% extends 'base.html' %} 
{% block title %}Adminka - Create Notification{% endblock %} 
{% block content %}
<main class="my-5 container">
    {% include 'includes/breadcrumbs/create-breadcrumb.html' with model=notification name="Notification"%}
    <div class="rounded-3 p-3 mb-5 shadow-lg">
        <h1 class="h3">General info</h1>
        <form method="post" id="model">
          {% csrf_token %}
            {{form}}
        </form>
    </div>
</main>
{% endblock %}

adminka/templates/notifications/notifications.html
{% extends 'base.html' %}
{% block title %}Adminka - Notifications{% endblock %}
{% block content %}
<main class="my-5 container">
    {% include 'includes/filter.html' with model="notification"%}
    <div class="p-4 shadow-lg mt-5 rounded-3">
        <div class="d-flex justify-content-between">
            <h1 class="fs-3 fw-bold text-center">Notifications</h1>
            <a href="{% url 'create-notification' %}" class="text-primary"
                ><i class="fa-solid fa-circle-plus fs-1"></i
            ></a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Text</th>
                    <th scope="col">Type</th>
                    <th scope="col">Date start</th>
                    <th scope="col">Date end</th>
                </tr>
            </thead>
            <tbody>
                {% for notification in notifications %}
                 <tr>
                    <th scope="row"> <a href="{% url 'view-notification' notification.id %}">{{notification.id}}</a> </th>
                    <td><a href="{% url 'view-notification' notification.id %}">{{notification}}</a> </td>
                    <td>{{notification.get_type_display}}</td>
                    <td>{{notification.start|date:'Y-m-d'}}</td>
                    <td>{{notification.end|date:'Y-m-d'}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include 'includes/pagination.html' with objects=notifications%}
    </div>
</main>
{% endblock  %}

adminka/templates/notifications/update-notification.html
{% extends 'base.html' %} 
{% block title %}Adminka - Update Notification: {{notification}}{% endblock %} 
{% block content %}
<main class="my-5 container">
    {% include 'includes/breadcrumbs/update-breadcrumb.html' with model=notification name="Notification" %}
    <div class="rounded-3 p-3 mb-5 shadow-lg">
        <h1 class="h3">General info</h1>
        <form method="post" id="model">
          {% csrf_token %}
            {{form}}
        </div>
        </form>
    </div>
</main>
{% endblock %}

adminka/templates/notifications/view-notification.html
{% extends 'base.html' %} 
{% block title %}Adminka - Notification:{{notification}}{% endblock %} 
{% block content %}
<main class="my-5 container">
    {% include 'includes/breadcrumbs/view-breadcrumb.html' with model=notification name="Notification" %}
    {% include 'includes/delete-modal.html' with model="notification" object=notification%}
    <div class="rounded-3 p-3 mb-5 shadow-lg">
        <h1 class="h3">General info</h1>
        {{form}}
        <div class="mb-3">
            <label for="created" class="form-label">Date created</label>
            <input
                type="date"
                class="form-control"
                id="created"
                value="{{notification.created|date:'Y-m-d'}}"
                disabled
            />
        </div>
    </div>
</main>
{% endblock %}